services:
  backend:
    container_name: backend
    image: avmukhortova/backend-kupipodariday
    env_file: .env
    ports:
      - 4000:3000
    networks:
      - internal

  frontend:
    container_name: frontend
    image: avmukhortova/frontend-kupipodariday
    ports:
      - 8081:80
    networks:
      - external

  postgres:
    container_name: postgres
    image: postgres:alpine
    env_file: .env
    restart: always
    volumes:
      - postgres_data:/data/postgres
    networks:
      - internal

  adminer:
    image: adminer
    restart: always
    ports:
      - 8082:8080
    networks:
      - internal

volumes:
  postgres_data: 

networks:
  internal:
  external: